### ISSUE TITLE
system nullreference exception

### ISSUE THREAD

**Issue by russozl** [ionutradu252/acspi#1]
![image](https://user-images.githubusercontent.com/102490193/160303505-d699f0b3-9913-4ca0-afdd-88c6a6d3eb9b.png)

I am getting this error when opening my servers: object reference not defined for a instance of an object

**Comment by ionutradu252** [comment]
> ![image](https://user-images.githubusercontent.com/102490193/160303505-d699f0b3-9913-4ca0-afdd-88c6a6d3eb9b.png)
> 
> I am getting this error when opening my servers: object reference not defined for a instance of an object

are you getting this while opening or while trying to create a pack?

**Comment by russozl** [comment]
> > ![imagem](https://user-images.githubusercontent.com/102490193/160303505-d699f0b3-9913-4ca0-afdd-88c6a6d3eb9b.png)
> > Estou recebendo este erro ao abrir meus servidores: referência de objeto não definida para uma instância de um objeto
> 
> você está recebendo isso ao abrir ou ao tentar criar um pacote?

when opening, it doesn't let me select any option, the error appears right away

**Comment by ionutradu252** [comment]
> > > ![imagem](https://user-images.githubusercontent.com/102490193/160303505-d699f0b3-9913-4ca0-afdd-88c6a6d3eb9b.png)
> > > Estou recebendo este erro ao abrir meus servidores: referência de objeto não definida para uma instância de um objeto
> > 
> > 
> > você está recebendo isso ao abrir ou ao tentar criar um pacote?
> 
> when opening, it doesn't let me select any option, the error appears right away

Thank you for your feedback! Issue should be fixed in latest HOTFIX 2, download again and try it out!

**Comment by russozl** [comment]
Hello, I have updated to the latest version and I still get the same error. I deleted all the files, ran as adm, but nothing works. 

If I try to ignore the error and create the pack anyway, it results in another error: 

an unhandled exception occurred in the application. If you click continue the application will ignore this error and try to continue.

The index was out of range. It must be-not negative and smaller than the collection size.
Parameter name: index


I also tried to delete my servers folder to see if it wasn't a conflict.


![image](https://user-images.githubusercontent.com/102490193/160613412-4220394e-0760-4eb3-aa9f-6cfc28e8213d.png)

**Comment by ionutradu252** [comment]
> Hello, I have updated to the latest version and I still get the same error. I deleted all the files, ran as adm, but nothing works.
> 
> If I try to ignore the error and create the pack anyway, it results in another error:
> 
> an unhandled exception occurred in the application. If you click continue the application will ignore this error and try to continue.
> 
> The index was out of range. It must be-not negative and smaller than the collection size. Parameter name: index
> 
> I also tried to delete my servers folder to see if it wasn't a conflict.
> 
> ![image](https://user-images.githubusercontent.com/102490193/160613412-4220394e-0760-4eb3-aa9f-6cfc28e8213d.png)

I've made multiple changes to the code, check it out now... it should work
